from tkinter import *
from tkinter import ttk

from my_modyl import README,examplecat,my_github,antiOpera,Antivirus
root = Tk()
root.title("i")
root.geometry("500x500")
root.resizable(width=500,height=500)

label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="my games")
label.pack()
label = ttk.Label(text="snake")
label.pack()
btn1 = ttk.Button(text="download", command=README)
btn1.pack(anchor="nw",padx=210, pady=0)
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="my programs")
label.pack()
label = ttk.Label(text="Anti-Opera")
label.pack()
btn1 = ttk.Button(text="download", command=antiOpera)
btn1.pack(anchor="nw",padx=210, pady=0)
label = ttk.Label(text="Antivirus")
label.pack()
btn1 = ttk.Button(text="download", command=Antivirus)
btn1.pack(anchor="nw",padx=210, pady=0)
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="my sites")
label.pack()
btn1 = ttk.Button(text="examplecat", command=examplecat)
btn1.pack(anchor="nw",padx=210, pady=0)
btn1 = ttk.Button(text="my github", command=my_github)
btn1.pack(anchor="nw",padx=210, pady=0)
root.mainloop()