from tkinter import *
from tkinter import ttk

from my_modyl import README,examplecat,my_github,antiOpera,Antivirus
root = Tk()
root.title("i")
root.geometry("500x500")
root.resizable(width=500,height=500)

label = ttk.Label(text="мои игры")
label.pack()
label = ttk.Label(text="змейка")
label.pack()
btn1 = ttk.Button(text="скачать", command=README)
btn1.pack(anchor="nw",padx=210, pady=0)
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="мои програмы")
label.pack()
label = ttk.Label(text="Anti-Opera")
label.pack()
btn1 = ttk.Button(text="скачать", command=antiOpera)
btn1.pack(anchor="nw",padx=210, pady=0)
label = ttk.Label(text="Antivirus")
label.pack()
btn1 = ttk.Button(text="скачать", command=Antivirus)
btn1.pack(anchor="nw",padx=210, pady=0)
label = ttk.Label(text="")
label.pack()
label = ttk.Label(text="мои сайты")
label.pack()
btn1 = ttk.Button(text="examplecat", command=examplecat)
btn1.pack(anchor="nw",padx=210, pady=0)
btn1 = ttk.Button(text="мой гитхаб", command=my_github)
btn1.pack(anchor="nw",padx=210, pady=0)
root.mainloop()